apiVersion: apps/v1
kind: Deployment
metadata:
  name: Course
  labels:
    app: Course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Course
  template:
    metadata:
      labels:
        app: Course
    spec:
      containers:
        - name: Course
          image: username/Course:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5