---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "student"
    labels: 
      app: "student"
  spec: 
    selector: 
      matchLabels: 
        app: "student"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "student"
      spec: 
        containers: 
          - 
            name: "student"
            image: "student"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "student"
    labels: 
      app: "student"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "student"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "course"
    labels: 
      app: "course"
  spec: 
    selector: 
      matchLabels: 
        app: "course"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "course"
      spec: 
        containers: 
          - 
            name: "course"
            image: "course"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "course"
    labels: 
      app: "course"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "course"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "enrollment"
    labels: 
      app: "enrollment"
  spec: 
    selector: 
      matchLabels: 
        app: "enrollment"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "enrollment"
      spec: 
        containers: 
          - 
            name: "enrollment"
            image: "enrollment"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "enrollment"
    labels: 
      app: "enrollment"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "enrollment"
